apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llmserve-pdb
  namespace: llmserve
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app.kubernetes.io/name: llmserve
      app.kubernetes.io/component: api
