apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvpages-pvc
  namespace: llmserve
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Gi
  storageClassName: fast-nvme
