# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import llmserve_pb2 as llmserve__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llmserve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrefillServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrefillChunk = channel.unary_unary(
                '/llmserve.v1.PrefillService/PrefillChunk',
                request_serializer=llmserve__pb2.PrefillChunkRequest.SerializeToString,
                response_deserializer=llmserve__pb2.PrefillChunkReply.FromString,
                _registered_method=True)


class PrefillServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrefillChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrefillChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefillChunk,
                    request_deserializer=llmserve__pb2.PrefillChunkRequest.FromString,
                    response_serializer=llmserve__pb2.PrefillChunkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmserve.v1.PrefillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmserve.v1.PrefillService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrefillService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrefillChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmserve.v1.PrefillService/PrefillChunk',
            llmserve__pb2.PrefillChunkRequest.SerializeToString,
            llmserve__pb2.PrefillChunkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DecodeStream = channel.unary_stream(
                '/llmserve.v1.DecodeService/DecodeStream',
                request_serializer=llmserve__pb2.DecodeRequest.SerializeToString,
                response_deserializer=llmserve__pb2.DecodeChunk.FromString,
                _registered_method=True)


class DecodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DecodeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DecodeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.DecodeStream,
                    request_deserializer=llmserve__pb2.DecodeRequest.FromString,
                    response_serializer=llmserve__pb2.DecodeChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmserve.v1.DecodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmserve.v1.DecodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DecodeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llmserve.v1.DecodeService/DecodeStream',
            llmserve__pb2.DecodeRequest.SerializeToString,
            llmserve__pb2.DecodeChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
