# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmserve.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llmserve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ellmserve.proto\x12\x0bllmserve.v1\"l\n\x13PrefillChunkRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x13\n\x0bstart_token\x18\x03 \x01(\x05\x12\x10\n\x08n_tokens\x18\x04 \x01(\x05\x12\x0e\n\x06tenant\x18\x05 \x01(\t\"I\n\x11PrefillChunkReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x11\n\tkv_handle\x18\x03 \x01(\t\"\xa0\x01\n\rDecodeRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0e\n\x06tenant\x18\x03 \x01(\t\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\x12\x13\n\x0btemperature\x18\x05 \x01(\x02\x12\r\n\x05top_p\x18\x06 \x01(\x02\x12\x15\n\rstrategy_hint\x18\x07 \x01(\t\x12\x10\n\x08workload\x18\x08 \x01(\t\"\x1c\n\x0b\x44\x65\x63odeChunk\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t2b\n\x0ePrefillService\x12P\n\x0cPrefillChunk\x12 .llmserve.v1.PrefillChunkRequest\x1a\x1e.llmserve.v1.PrefillChunkReply2W\n\rDecodeService\x12\x46\n\x0c\x44\x65\x63odeStream\x12\x1a.llmserve.v1.DecodeRequest\x1a\x18.llmserve.v1.DecodeChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmserve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREFILLCHUNKREQUEST']._serialized_start=31
  _globals['_PREFILLCHUNKREQUEST']._serialized_end=139
  _globals['_PREFILLCHUNKREPLY']._serialized_start=141
  _globals['_PREFILLCHUNKREPLY']._serialized_end=214
  _globals['_DECODEREQUEST']._serialized_start=217
  _globals['_DECODEREQUEST']._serialized_end=377
  _globals['_DECODECHUNK']._serialized_start=379
  _globals['_DECODECHUNK']._serialized_end=407
  _globals['_PREFILLSERVICE']._serialized_start=409
  _globals['_PREFILLSERVICE']._serialized_end=507
  _globals['_DECODESERVICE']._serialized_start=509
  _globals['_DECODESERVICE']._serialized_end=596
# @@protoc_insertion_point(module_scope)
